### ISSUE TITLE
file_put_contents - failed to open stream: File name too long

### ISSUE THREAD

**Issue by fabcom-yoni** [meatpaste/ee-rocket-docs#1]
Plugin has been working great, but recently we've had an issue where the generated cache filename is too large:

For example:
`file_put_contents(/var/www/html/atsu/rocket_cache/L2NvbnRhY3QtYXRzdT91dG1fY2FtcGFpZ249bm4tYXRzdS1jZ2hzLTIxMjItcGhhc2UtMS1hbm51YWwtY2FtcGFpZ24tbWhzYyZ1dG1fc291cmNlPWdvb2dsZSZ1dG1fbWVkaXVtPWNwYyZ1dG1fdGVybT1hdCUyMHN0aWxsJTIwaGVhbHRoJTIwc2NpZW5jZXMmY2FtcGFpZ25faWQ9MTQ1ODM0NzI5OTEmZ2NsaWQ9Q2owS0NRanc1SlNMQmhDeEFSSXNBSGdPMlNmcHJGSlFJLWZ2aUc4ZmhnWFVwM3gxcFB5SWhXbTFHNDY1UGdPTnhvU0V3M1V2c29ndWJ0a2FBcnVGRUFMd193Y0I=.html): failed to open stream: File name too long`

There's generally a 255 character OS limit, so it would be great if the max length of the cached filename was limited.

**Comment by meatpaste** [comment]
could you let me know the URL which generated this hash so that I can investigate?

**Comment by fabcom-yoni** [comment]
it was from editing this page: https://www.atsu.edu/contact-atsu

**Comment by meatpaste** [comment]
working on a fix now 👍

**Comment by meatpaste** [comment]
please update to 2.1.0 which i've just posted on the EE site, and make use of the 'URL Exceptions' feature which will make rocket ignore tracking url parameters
