### ISSUE TITLE
Cannot change session cookie parameters when session is active

### ISSUE THREAD

**Issue by karlosb** [meatpaste/ee-rocket-docs#2]
Hi Roger,

Just started getting this message when using the // START ROCKET script for in top levelv index.php (running  latest ee6.1.5 release):

session_set_cookie_params(): Cannot change session cookie parameters when session is active

ee/legacy/libraries/Core.php, line 139

    Severity: E_WARNING

any ideas how to resolve?

Many thanks in advance.

Kind Regards
Karl

**Comment by meatpaste** [comment]
can you try putting this at the end of the snippet and see if it resolves the issue? i've not been able to recreate it here.

`session_destroy();`

**Comment by karlosb** [comment]
Hi Roger,

Many thanks for the feedback on this.

I think we've resoled the issue as we recently switched servers for the site and the snippet does not appear to be causing any issues now.

If the issue arrises again I will try the `session_destroy();` line as advised above.

Kind Regards
Karl

**Comment by meatpaste** [comment]
@karlosb Managed to recreate this on my dev environment, that line worked to resolve it so that will make its way into the next release 👍

**Comment by karlosb** [comment]
Hi @meatpaste yes I ended up getting the PHP error message again, so I added the line at this end and it appears to be working great. 😀👍
