### ISSUE TITLE
Is A Directory Error

### ISSUE THREAD

**Issue by marc524** [meatpaste/ee-rocket-docs#4]
Upon saving an entry I get the error message:
**file_put_contents(/home/forge/domain.com/web/rocket_cache/cache/product-info/): Failed to open stream: Is a directory**
**user/addons/rocket/ext.rocket.php, line 65**

When I load the page I get the error message:
**file_get_contents(): Read of 8192 bytes failed with errno=21 Is a directory**
**user/addons/rocket/ext.rocket.php, line 198**

The directory was created, but no files were created in that folder.

For settings I have minify off, yes to update on save, and exclude set, but no paths in the Exceptions box.

Rocket 2.1.3
EE 6.1.0

Thoughts?

Edit: Ok, I'm realizing that it is not caching the index.html nor is it recognizing that path without adding it.
Thus: 
http://domain.com/product-info/index.html gets cached and works.
http://domain.com/product-info does not work and results in the errors.

Although there is still the save error.

**Comment by SETU-WEB** [comment]
Yes I Have a similar issue, but Im not getting that error I do get this warning on the page 
file_put_contents(/var/www/html/rocket_cache/cache/schools/business/school_of_business/welcome_from_the_head_of_school/): failed to open stream: No such file or directory
user/addons/rocket/ext.rocket.php, line 65
Rocket 2.1.3
EE 5.4.3
I get that warning in Chrome but get a while screen in Microsoft Edge. In the rocket cache folder, the folders are being made but they have nothing in them 
Thanks

**Comment by meatpaste** [comment]
thanks, i've just pushed a fix to the store, 2.1.4

**Comment by marc524** [comment]
Thanks. That seems to have fixed it.
